// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOa_QpB8XdslXGtVSlimy3zZ7VH0h1tjI',
    appId: '1:643310975193:web:7d9019f9028ecbab27a6c8',
    messagingSenderId: '643310975193',
    projectId: 'goaviralnews-83e6a',
    authDomain: 'goaviralnews-83e6a.firebaseapp.com',
    storageBucket: 'goaviralnews-83e6a.appspot.com',
    measurementId: 'G-MW793TJHNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWiq9FbU5vy8SANKSb5C0XidjpFPij9FQ',
    appId: '1:643310975193:android:1feeb43faa4106a727a6c8',
    messagingSenderId: '643310975193',
    projectId: 'goaviralnews-83e6a',
    storageBucket: 'goaviralnews-83e6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwQAigyq1NPoJypTg-JeqWRLVqgOBaaek',
    appId: '1:643310975193:ios:cf434398bc45183d27a6c8',
    messagingSenderId: '643310975193',
    projectId: 'goaviralnews-83e6a',
    storageBucket: 'goaviralnews-83e6a.appspot.com',
    androidClientId: '643310975193-mbfhq1688boanqnjbvdv1p1np9v7kd34.apps.googleusercontent.com',
    iosClientId: '643310975193-7gkoj4j3ffgqfninfef4vp87s3hj57da.apps.googleusercontent.com',
    iosBundleId: 'com.example.goaviralnews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwQAigyq1NPoJypTg-JeqWRLVqgOBaaek',
    appId: '1:643310975193:ios:cf434398bc45183d27a6c8',
    messagingSenderId: '643310975193',
    projectId: 'goaviralnews-83e6a',
    storageBucket: 'goaviralnews-83e6a.appspot.com',
    androidClientId: '643310975193-mbfhq1688boanqnjbvdv1p1np9v7kd34.apps.googleusercontent.com',
    iosClientId: '643310975193-7gkoj4j3ffgqfninfef4vp87s3hj57da.apps.googleusercontent.com',
    iosBundleId: 'com.example.goaviralnews',
  );
}
